### ISSUE TITLE
ZAP Search Web API implementation (ETL is failing to obtain all records)

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#1159]
I'm synthesizing several issues into one, because I think they all have the same root problem: the skyvia ETL is failing to obtain all records from ZAP CRM. We need to fix whatever is causing the ETL to do an incomplete transfer.

Once we fix the ETL, we can reopen any of these sub-issues if there is a remaining problem.

**Checklist of issues to make sure are solved:**
- [ ] #1150 Number of projects for each filter on Zap Search do not match the number of projects on CRM
- [ ] #1152 Number of Projects for LD action type on ZAP search, do not match ZAP Data
- [ ] #1122 Skyvia failures: dcp_projects
- [ ] #1119 Skyvia failures: dcp_projectbbl
- [ ] #1123 Skyvia failures: projectactions

#### Update:
We have created an experimental deployment of ZAP Search that uses Microsoft's Web API instead of an ETL and a separate database. It's ready for testing at https://api-only-experiment--labs-zap.netlify.com/projects

**Comment by allthesignals** [comment]
Ways forward on this:

 - [ ] Get a test going on the Postgres 11 theory on ZAP Staging. If this works, it might make the ETL replacement need a bit less urgent
 - [ ] Disable foreign key constraints

**Comment by allthesignals** [comment]
Here's the constraint: 

We can't use managed postgres because ST_MVT requires a low-level dependency that Digital Ocean does not have installed on its managed postgres SaaS product.

Because ZAP API uses ST_MVT functions on a Postgres instance, we can't used managed postgres.

The other issue is that **I believe** the Skyvia ETLs are partially failing because of Postgres versions. Our current db server runs PG 10. Managed PG is PG11.

Some paths forward:
 - FDW from ZAP API's DB Server into EDM's CRM Replication Server
 - Upgrade Postgres on DB Server to 11; rerun ETL
 - Degrade map functionality and temporary point ZAP API to EDM
 - Switch map to Carto instead; point to Managed Postgres

**Comment by bfreeds** [comment]
Tested this:
> Upgrade Postgres on DB Server to 11 -> rerun ETL on fresh database database from skyvia -> run migrations -> copy the spatial table into the new fresh db

By creating a new database container on our digital ocean droplet.  Within that dockerized postgres cluster, I created two databases (`zap_pg11_test` and `zap_pg11_test_no_foreign_keys`).

I setup two Skyvia integrations to try the integration with foreign keys and without foreign keys, to see if not including the foreign keys might get past the foreign key error @allthesignals discovered in the previous Skyvia error logs.  

![image](https://user-images.githubusercontent.com/5316367/76126084-2fe93080-5fcc-11ea-82b8-6485d979dc1c.png)

We can't view the Skyvia logs on these until the integrations finish, but we _can_ see that there are errors being logged.

**Comment by allthesignals** [comment]
Here's where we landed: 
 - Use EDM's successfully loading Skyvia database as the production database
 - Disable the map to get around the low-level dependency req

Todo asap:
 - Create a new ETL target and get off EDM
 - Discover strategy forward with map

**Comment by allthesignals** [comment]
Creating a new ETL into Managed PG

**Comment by allthesignals** [comment]
Can we see about cleaning up Skyvia? There are a lot of unused connections and "packages" (integrations) on it...

**Comment by allthesignals** [comment]
Migrating the prod site to the safer db, setting up a UAT2 -> staging in Skyvia

**Comment by allthesignals** [comment]
I was seeing some strange errors:

> Run ID 34191819: An error occurred with the following error message: "Transport channel is closed."
> Run ID 34190004: An exception has occurred during initialization: Updating field with name dcp_projectactionid does not exist in schema table.
> Run ID 34188331: An error occurred with the following error message: "remaining connection slots are reserved for non-replication superuser connections"

I'm not sure what the cause of the second error was. The other errors I think have to do with our postgres "node" on digital ocean. I went ahead and increased the memory capacity of it.
