### ISSUE TITLE
Update milestones to match new ZAP db schema

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#450]
Imminent ZAP db schema changes include changes to the text labels used for milestones. The labels are captured in the `dcp_milestones` table. The change to the labels will break the project profiles in ZAP Search, since the milestones labels are used to produce the milestone timeline in the front-end. Note: the preferred milestone labels used for public consumption on the profiles will stay the same.

**Work done already:**
- [x] Swapped in the new milestone labels. This should be the only change required. https://github.com/NYCPlanning/labs-zap-search/compare/450-db-schema-change?expand=1

**Work in prep for ZAP changes deployment:**
- [x] Switch ZAP Search over to temporary "under construction page"

**Work remaining once the ZAP changes are deployed:**
- [x] Confirm database tables are the same as expected, with only change being the new labels in `dcp_milestones`
- [ ] Test and merge updates from https://github.com/NYCPlanning/labs-zap-search/compare/450-db-schema-change?expand=1
- [ ] Switch back the live ZAP Search view with new milestones

**Milestones that will be changes in ZAP schema update:**

Original | New Proposed Name | Used in ZAP Search
-- | -- | --
Land Use Fee Invoice Review | Review Filed Land Use Fee Invoice | No
Land Use Fee Payment | Prepare Filed Land Use Fee Payment | Yes
Land Use Application Filed Review | Review Filed Land Use Application | No, but "Revised Land Use Application Filed Review" is used
Prepare EIS Draft Scope | Prepare EIS Draft Scope of Work | No
EIS Draft Scope Review | Review Filed EAS and EIS Draft Scope of Work | Yes
CEQR Fee Invoice Review | Review CEQR Fee Invoice | No
CEQR Fee Payment | Prepare CEQR Fee Payment | Yes
Filed EAS Review | Review Filed EAS | Yes
EIS Public Scoping Meeting | DEIS Public Scoping Meeting | Yes
Prepare and Review PDEIS Chapters | Prepare and Review DEIS | No
Final Scope of Work Issued | Issue Final Scope of Work | Yes
NOC of Draft EIS Issued | DEIS Notice of Completion Issued | Yes
FEIS Submitted and Review | Prepare and Review FEIS | Yes

**Comment by andycochran** [comment]
https://nycplanning.github.io/labs-app-currently-down/
