### ISSUE TITLE
New milestone + milestone ordering improvements

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#458]
**1. Land use application filed and fee payment**

- Current state: There can be multiple, valid "land use application filed" milestones, because applicant can file revisions to their application. Currently, the "fee paid" milestone shows up after all of the "land use application filed" milestones, even though it happened before the later revisions
- Preferred state: 
  - [x] All "land use application filed" and "fee paid" milestones should be listed in chronological order
  - [x] Each "land use application filed" milestone that comes after the first one, should indicate that it's a revision to it doesn't look like a data error. It can be called "Revised land use application filed"
- Example reference project: https://zap.planning.nyc.gov/projects/P2013K0549

**2. New "CPC Review of Council Modification" milestone**

- Requirements:
  - [x] "CPC review of modification scope" (<- title in ZAP) needs to be inserted (if it exists) between the two city council reviews
  - [x] Preferred label for ZAP Search: "CPC Review of Council Modification"
  - [x] Display the "actual completion date"
- Example reference project: https://zap.planning.nyc.gov/projects/P2018X0138
