### ISSUE TITLE
Super Filter Redesign

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#467]
The existing project description filter will be expanded to include searches for
- [ ] Keywords
- [x] CEQR numbers
- [x] ULURP numbers
- [ ] BBLs

This implementation should also remove the unnecessary individual filters for
- [x] ULURP and CEQR numbers
- [ ] ULURP type
- [x] CEQR type!

Additional changes to be implemented as a part of the redesign
- [x] Header and move reset button to top
- [x] Change label and prompt for consolidated text filter
- [x] Remove project status filter from default filter settings. Most users want to see all projects.

Screenshot mockup:
![image](https://user-images.githubusercontent.com/13967925/55728366-f128b000-59e1-11e9-8b9f-671f89d4057b.png)

**Comment by hannahkates** [comment]
Text match "Search for an exact phrase, name, or number"
