### ISSUE TITLE
[new API] Revised application filing milestone is missing on 2019R0291

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#577]
The "Revised Land Use Application Filed" milestone is completely missing on project 2019R0291. It seems like we aren't querying for all the milestones that we should be or some are being filtered out. 2019R0291https://zap.planning.nyc.gov/projects/2019R0291

**Comment by allthesignals** [comment]
This appears to have more to do with hard-coded ids being used to in the front-end to prefix the title with the word "Revised", see the `revisedmilestones` computed property in show-project controller.

The # of milestones returned is also affected by this filter:

```
          `<filter>`,
            `<condition attribute="statuscode" operator="ne" value="${STATUSCODE.OVERRIDDEN}" />`,
          `</filter>`,
```

I'm not sure why this filter was added... @hannahkates any ideas why? OVERRIDDEN is a constant `717170001`. Looks like some identifier.

**Comment by allthesignals** [comment]
See the comment: https://github.com/NYCPlanning/labs-zap-search/blob/develop/app/controllers/show-project.js#L34-L62

**Comment by allthesignals** [comment]
@hannahkates that said, can we not change the titles in CRM rather than mapping in a crosswalk in our API? I think if not, we should create a new issues that better organizes the business logic and data for vanity name crosswalks like ones in the milestones SQL.

**Comment by hannahkates** [comment]
Re: IDs in the front-end, those were selected because they are the two types of the milestones that often have many revisions. The IDs were pulled from the dcp_milestone table based on the label in dcp_name. Running the SQL below, they still appear to be the IDs we want. The resulting labels are 'Prepare Filed Land Use Application' and 'Review Filed EAS'

```
SELECT dcp_milestoneid, dcp_name 
FROM dcp_milestone
WHERE dcp_milestoneid IN (
  '663beec4-dad0-e711-8116-1458d04e2fb8', 
  '783beec4-dad0-e711-8116-1458d04e2fb8'
)
```

Re: OVERRIDDEN, I have no clue. I don't remember that being in the old SQL query.

**Comment by hannahkates** [comment]
The milestoneIDs used for 'Land Use Fee Paid' and 'Community Board Review' and in the constants file (https://github.com/NYCPlanning/labs-zap-api/blob/zap-api-with-CRM/constants.js#L98) match the old ones in show.sql (https://github.com/NYCPlanning/labs-zap-api/blob/develop/queries/projects/show.sql), so I'm confused on where the mismatch is coming from.

@allthesignals what do you have in mind for "create a new issues that better organizes the business logic and data for vanity name crosswalks like ones in the milestones SQL" beyond what's already in https://github.com/NYCPlanning/labs-zap-api/blob/zap-api-with-CRM/constants.js?

**Comment by hannahkates** [comment]
Final solution to implement (based on troubleshooting):
- [ ] Overridden filter is necessary and should stay intact
- [ ] Milestones are being deduped incorrectly. We need to add a date column to the dedupeList() function here https://github.com/NYCPlanning/labs-zap-api/blob/zap-api-with-CRM/utils/project/flatten-rows.js#L48
- [ ] Actions are being deduped incorrectly. We need to add the ULURP number column to the dedupeList() function here https://github.com/NYCPlanning/labs-zap-api/blob/zap-api-with-CRM/utils/project/flatten-rows.js#L46

**Comment by allthesignals** [comment]
https://zap.planning.nyc.gov/projects/P2018M0104

The last milestone is not appearing for me in local dev

**Comment by allthesignals** [comment]
- [ ] Restore the milestoneLinks

**Comment by allthesignals** [comment]
@hannahkates making progress — the only discrepancy I'm seeing is the very last milestone, which is missing from my direct-CRM source branch:

![Screen Shot 2019-08-14 at 10.20.24 AM.png](https://images.zenhubusercontent.com/5ca23922d9fcf5278d715977/6f8ea489-93c0-4ef3-95f5-308656f20a50)

![Screen Shot 2019-08-14 at 10.20.21 AM.png](https://images.zenhubusercontent.com/5ca23922d9fcf5278d715977/e29d478a-bf95-489f-b90d-ecfec386d5f7)
