### ISSUE TITLE
Investigate data display issues

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#921]
Several projects we're heard complaints about and need to investigate:

Project: Madigan Place
- [ ] Three actions should be appearing but only one is. **[hk: the show.sql query is returning all 3 actions, but they are missing in the API response. i think something is wrong with the serialization https://github.com/NYCPlanning/zap-api/issues/7]**

Project: Industry City Land Use. 
- [ ] All prepare filed milestones are not appearing. (there should be 4) **[hk: the show.sql query is returning all 4 filing milestones, but they are missing in the API response. i think something is wrong with the serialization https://github.com/NYCPlanning/zap-api/issues/7]**
- [x] The land use actions application shows up as “filed” rather than “in public review” in the project filter list. When you navigate to the project record (click on it), it does say “in public review”. These two fields should match. **[hk: the statuses match on staging now]**

Project: Industry City City Map
- [x] The city map change application does not show up on the portal at all when you search for it just using the Community District 7 filter or if via the text match function. Prior to the latest update it did show up. You can get to it in other ways if you add other search criteria. **[hk: can't replicate this problem; the project appears on prod and staging]**

Project: 375 Pearl Street - POPS Redesign
- [ ] Applicant name is not appearing. It should pull from the primary applicant field on the project record (not applicant team). System should pull co-applicants from the Applicant team where the ‘applicant team’ record is ‘active’ and the role equals ‘co-applicant’ **[hk: this is different from current implementation. need to create a new issue [https://github.com/NYCPlanning/zap-api/issues/33](https://github.com/NYCPlanning/zap-api/issues/33) ]**

Project: 5914 Bay Parkway
- [ ] 5914 Bay Parkway’s Zoning Application Portal, AppendixF link sends you to the below error page. Should go here: https://zr.planning.nyc.gov/appendix-f-inclusionary-housing-designated-areas-and-mandatory-inclusionary-housing-areas **[hk: we should create an issue to link to online ZR sections instead [https://github.com/NYCPlanning/labs-zap-search/issues/925](https://github.com/NYCPlanning/labs-zap-search/issues/925) ]**
